### ISSUE TITLE
Дублирование правил в css

### ISSUE THREAD

**Issue by mixalezhnev** [pyxarez/Todo#14]
`body, html {
  height: 100%;
}
`

`#root {
  height: 100%;
}`

**Comment by pyxarez** [comment]
@mixalezhnev нету дублирования

**Comment by pyxarez** [comment]
![image](https://cloud.githubusercontent.com/assets/23152279/24663827/168078c0-196a-11e7-9d93-f2f309f42765.png)

**Comment by mixalezhnev** [comment]
`#root, body, html { height: 100%; }`
Теперь нету

**Comment by pyxarez** [comment]
Хмм
Вот это зашквар

**Comment by pyxarez** [comment]
Пофиксил
